"""Add invoices model

Revision ID: 04e62380580f
Revises: a902d2103e77
Create Date: 2026-01-24 22:06:43.481702

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "04e62380580f"
down_revision: Union[str, Sequence[str], None] = "a902d2103e77"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "odooinvoices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("odoo_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=256), nullable=True),
        sa.Column("partner_id", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("invoice_date", sa.String(length=256), nullable=True),
        sa.Column("amount_total", sa.Float(), nullable=True),
        sa.Column("state", sa.String(length=256), nullable=True),
        sa.Column("move_type", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_odooinvoices_id"), "odooinvoices", ["id"], unique=False)
    op.create_index(
        op.f("ix_odooinvoices_name"), "odooinvoices", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_odooinvoices_odoo_id"), "odooinvoices", ["odoo_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_odooinvoices_odoo_id"), table_name="odooinvoices")
    op.drop_index(op.f("ix_odooinvoices_name"), table_name="odooinvoices")
    op.drop_index(op.f("ix_odooinvoices_id"), table_name="odooinvoices")
    op.drop_table("odooinvoices")
    # ### end Alembic commands ###
