"""Add is_company flag

Revision ID: a570377ffbc1
Revises: f5954da6a4b2
Create Date: 2026-01-24 20:26:38.923715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a570377ffbc1'
down_revision: Union[str, Sequence[str], None] = 'f5954da6a4b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('odoocontacts', sa.Column('is_company', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odoocontacts', 'is_company')
    # ### end Alembic commands ###
