"""Add odoo contact table

Revision ID: f5954da6a4b2
Revises: 
Create Date: 2026-01-24 19:54:41.172036

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5954da6a4b2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odoocontacts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('odoo_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('company_name', sa.String(length=256), nullable=True),
    sa.Column('company_id', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odoocontacts_company_name'), 'odoocontacts', ['company_name'], unique=False)
    op.create_index(op.f('ix_odoocontacts_email'), 'odoocontacts', ['email'], unique=False)
    op.create_index(op.f('ix_odoocontacts_id'), 'odoocontacts', ['id'], unique=False)
    op.create_index(op.f('ix_odoocontacts_name'), 'odoocontacts', ['name'], unique=False)
    op.create_index(op.f('ix_odoocontacts_odoo_id'), 'odoocontacts', ['odoo_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odoocontacts_odoo_id'), table_name='odoocontacts')
    op.drop_index(op.f('ix_odoocontacts_name'), table_name='odoocontacts')
    op.drop_index(op.f('ix_odoocontacts_id'), table_name='odoocontacts')
    op.drop_index(op.f('ix_odoocontacts_email'), table_name='odoocontacts')
    op.drop_index(op.f('ix_odoocontacts_company_name'), table_name='odoocontacts')
    op.drop_table('odoocontacts')
    # ### end Alembic commands ###
